### ISSUE TITLE
More patterns don't match correctly.

### ISSUE THREAD

**Issue by pufmat** [becheran/wildmatch#19]
**Describe the bug**
Pattern `*1?` should not match `121`.
Pattern `*12` should not match `122`.
Pattern `*121` should match `12121`.

**To Reproduce**
```rs
assert!(WildMatch::new("*1?").matches("121") == false);
assert!(WildMatch::new("*12").matches("122") == false);
assert!(WildMatch::new("*121").matches("12121") == true);
```

**Expected behavior**
Assertions should pass.

**Additional context**
`rustc 1.75.0 (82e1608df 2023-12-21)`

**Comment by becheran** [comment]
Meanwhile I have a random input test written which also fails on some inputs. I am working on a solution

**Comment by becheran** [comment]
I fixed the issues including a unit test which generates many random patterns to hopefuly also catch issues if there are still some.

Please upgrade to version `2.3.2`

I had to re-run the benchmarks and the matching performance decreased by the factor two which is kind of expected since I now iterate over the input twice since I create a vec of chars for precise indexing. I don't have a solution for that yet, but will close this issue and open another one to improve performance further if that is even possible. I don't know yet.
